Repository SOPT-all/35-COLLABORATION-SERVER-KORAILTALK, pull requests merged in 2024-11, with the labels that each got.

#1 [FEAT] : yaml 세팅
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: documentation

#3 [FEAT] : pr 템플릿 생성
  .github/pull_request_template.md
Labels: documentation

#4 [FEAT] : 공통 Response 작성 및 예외 처리 작성
  src/main/java/com/korailtalk/server/api/common/dto/APIErrorResponse.java
  src/main/java/com/korailtalk/server/api/common/dto/APISuccessResponse.java
  src/main/java/com/korailtalk/server/api/common/enums/ErrorStatus.java
  src/main/java/com/korailtalk/server/api/common/exception/BadRequestException.java
  src/main/java/com/korailtalk/server/api/common/exception/GlobalExceptionHandler.java
  src/main/java/com/korailtalk/server/api/common/exception/KorailException.java
  src/main/java/com/korailtalk/server/api/common/exception/NotFoundException.java
  src/main/java/com/korailtalk/server/api/common/exception/UnAuthorizedException.java
Labels: ✨ feature

#5 [FEAT] : issue 템플릿 생성
  .github/issue_template.md
Labels: 📃 docs

#8 [FEAT] : LPoint 조회 API 구현
  src/main/java/com/korailtalk/server/api/common/enums/ErrorStatus.java
  src/main/java/com/korailtalk/server/common/APIErrorResponse.java
  src/main/java/com/korailtalk/server/common/APISuccessResponse.java
  src/main/java/com/korailtalk/server/train/controller/tmp.txt
  src/main/java/com/korailtalk/server/train/dto/tmp.txt
  src/main/java/com/korailtalk/server/train/service/tmp.txt
  src/main/java/com/korailtalk/server/user/controller/UserController.java
  src/main/java/com/korailtalk/server/user/dto/resopnse/LPointsResponse.java
  src/main/java/com/korailtalk/server/user/service/UserService.java
  src/main/resources/application.yaml
Labels: ✨ feature

#13 [FEAT] : 티켓 발권 API
  src/main/java/com/korailtalk/server/api/ticket/controller/TicketController.java
  src/main/java/com/korailtalk/server/api/ticket/dto/request/TicketConfirmRequest.java
  src/main/java/com/korailtalk/server/api/ticket/service/TicketService.java
  src/main/java/com/korailtalk/server/api/user/service/UserService.java
  src/main/java/com/korailtalk/server/db/ticket/entity/Ticket.java
  src/main/java/com/korailtalk/server/db/user/entity/User.java
Labels: ✨ feature

#18 [FEAT] : 좌석 선택 API 구현
  src/main/java/com/korailtalk/server/api/common/enums/ErrorStatus.java
  src/main/java/com/korailtalk/server/api/seat/controller/SeatController.java
  src/main/java/com/korailtalk/server/api/seat/dto/request/SeatSelectRequest.java
  src/main/java/com/korailtalk/server/api/seat/dto/response/SeatSelectResponse.java
  src/main/java/com/korailtalk/server/api/seat/service/SeatService.java
  src/main/java/com/korailtalk/server/db/BaseTimeEntity.java
  src/main/java/com/korailtalk/server/db/seat/repository/SeatRepository.java
  src/main/java/com/korailtalk/server/db/ticket/entity/Ticket.java
  src/main/java/com/korailtalk/server/db/ticket/repository/TicketRepository.java
Labels: ✨ feature

#20 [REFACT] : 생성시간 자동 업데이트 적용
  src/main/java/com/korailtalk/server/db/BaseTimeEntity.java
Labels: 🐞 fix
